language: node_js
node_js:
  - "7"
script:
  - yarn test
  - yarn lint
  - yarn flow
  - yarn build
cache:
  yarn: true
deploy:
  - provider: script
    script: scripts/deploy.sh staging
    skip_cleanup: true
    on:
      branch: master
